import { mkdir, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const projectRoot = fileURLToPath(new URL('../', import.meta.url));
const fixture = fileURLToPath(new URL('./fixtures/openapi.yaml', import.meta.url));
const discriminatedFixture = fileURLToPath(
  new URL('./fixtures/discriminated-monitor-create.yaml', import.meta.url),
);
const ordinaryRequestFixture = fileURLToPath(
  new URL('./fixtures/ordinary-request-body.yaml', import.meta.url),
);

describe('OpenAPI command generation', () => {
  it('turns every operation into a deterministic oclif command entrypoint', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-'));
    const result = await runGenerator(['--input', fixture, '--output', output]);

    const operations = await readFile(join(output, 'generated/operations.ts'), 'utf8');
    const generatedFiles = (await readdir(join(output, 'generated'))).sort();
    const listCommand = await readFile(join(output, 'commands/monitors/list.ts'), 'utf8');
    const deleteCommand = await readFile(join(output, 'commands/monitors/delete.ts'), 'utf8');

    expect({ deleteCommand, generatedFiles, listCommand, operations, result }).toEqual({
      deleteCommand:
        "/**\n * Code generated by scripts/generate-openapi.ts\n * from openapi/openapi.yaml.\n *\n * DO NOT EDIT — changes will be overwritten.\n * Run `pnpm openapi:generate` to regenerate.\n */\nimport { createOperationCommand } from '../../lib/operation-command.js';\nimport { operations } from '../../generated/operations.js';\n\nexport default createOperationCommand(operations['monitors:delete']);\n",
      listCommand:
        "/**\n * Code generated by scripts/generate-openapi.ts\n * from openapi/openapi.yaml.\n *\n * DO NOT EDIT — changes will be overwritten.\n * Run `pnpm openapi:generate` to regenerate.\n */\nimport { createOperationCommand } from '../../lib/operation-command.js';\nimport { operations } from '../../generated/operations.js';\n\nexport default createOperationCommand(operations['monitors:list']);\n",
      generatedFiles: ['command-files.json', 'operations.ts'],
      operations: expect.stringContaining('"commandId": "monitors:list"'),
      result: { exitCode: 0, stderr: '', stdout: 'Generated 2 commands.\n' },
    });
    expect(operations).toContain('"name": "includePaused"');
    expect(operations).toContain('"default": false');
    expect(operations).toContain('"example": true');
  });

  it('expands a discriminated request body into typed command entrypoints', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-discriminator-'));
    const result = await runGenerator(['--input', discriminatedFixture, '--output', output]);

    const commandFiles = await listFiles(join(output, 'commands'));
    const operations = await readFile(join(output, 'generated/operations.ts'), 'utf8');
    const httpCommand = await readFile(join(output, 'commands/monitors/create/http.ts'), 'utf8');

    expect(commandFiles.map((path) => relative(join(output, 'commands'), path))).toEqual([
      'monitors/create/heartbeat.ts',
      'monitors/create/http.ts',
    ]);
    await expect(
      readFile(join(output, 'commands/monitors/create.ts'), 'utf8'),
    ).rejects.toMatchObject({ code: 'ENOENT' });
    expect(httpCommand).toContain("operations['monitors:create:http']");
    expect(operations).toContain('"commandId": "monitors:create:http"');
    expect(operations).toContain('"requestBodyDefaults": {\n      "type": "HTTP"\n    }');
    expect(operations).toContain('"path": "friendlyName"');
    expect(operations).toContain('"flag": "name"');
    expect(operations).toContain('"path": "config.ipVersion"');
    expect(operations).toContain('"default": false');
    expect(operations).toContain('"path": "assignedAlertContacts"');
    expect(operations).toContain('"requiredProperties": [');
    expect(operations).toContain('"alertContactId"');
    expect(operations).toContain('"example": 12345');
    expect(operations).toContain('"summary": "Create a basic HTTP monitor"');
    expect(operations).toContain('"friendlyName": "Checkout"');
    expect(operations).not.toContain('"path": "type"');
    expect(result).toEqual({
      exitCode: 0,
      stderr: '',
      stdout: 'Generated 2 commands.\n',
    });
  });

  it('generates typed flags for an ordinary object request body', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-request-body-'));
    const result = await runGenerator(['--input', ordinaryRequestFixture, '--output', output]);

    const operations = await readFile(join(output, 'generated/operations.ts'), 'utf8');

    expect(operations).toContain('"commandId": "monitors:update"');
    expect(operations).toContain('"path": "friendlyName"');
    expect(operations).toContain('"flag": "name"');
    expect(operations).toContain('"path": "checkSSLErrors"');
    expect(operations).toContain('"flag": "check-ssl"');
    expect(operations).toContain('"path": "config.ipVersion"');
    expect(result).toEqual({
      exitCode: 0,
      stderr: '',
      stdout: 'Generated 1 commands.\n',
    });
  });

  it('covers every operation in the pinned public API contract', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-full-'));
    const contract = join(projectRoot, 'openapi/openapi.yaml');
    const result = await runGenerator(['--input', contract, '--output', output]);
    const commandFiles = await listFiles(join(output, 'commands'));
    const monitorCreateCommands = commandFiles
      .filter((path) => path.includes('/monitors/create/'))
      .map((path) => path.slice(path.lastIndexOf('/create/') + 8, -3))
      .sort();

    expect({
      bulkUpdate: commandFiles.some((path) => path.endsWith('/monitors/bulk/update.ts')),
      commandCount: commandFiles.length,
      genericMonitorCreate: commandFiles.some((path) => path.endsWith('/monitors/create.ts')),
      monitorCreateCommands,
      result,
    }).toEqual({
      bulkUpdate: true,
      commandCount: 67,
      genericMonitorCreate: false,
      monitorCreateCommands: [
        'api',
        'dns',
        'heartbeat',
        'http',
        'keyword',
        'ping',
        'port',
        'udp',
        'visual-comparison',
      ],
      result: { exitCode: 0, stderr: '', stdout: 'Generated 67 commands.\n' },
    });
  });

  it('preserves handwritten commands when regenerating OpenAPI commands', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-manual-'));
    const manualCommand = join(output, 'commands/auth/login.ts');
    await mkdir(join(output, 'commands/auth'), { recursive: true });
    await writeFile(manualCommand, 'export default class Login {}\n');

    const result = await runGenerator(['--input', fixture, '--output', output]);

    await expect(readFile(manualCommand, 'utf8')).resolves.toBe('export default class Login {}\n');
    expect(result).toEqual({ exitCode: 0, stderr: '', stdout: 'Generated 2 commands.\n' });
  });

  it('removes discriminator commands that disappear from the contract', async () => {
    const output = await mkdtemp(join(tmpdir(), 'uptimerobot-openapi-remove-variant-'));
    await runGenerator(['--input', discriminatedFixture, '--output', output]);

    expect(await listFiles(join(output, 'commands'))).toHaveLength(2);

    await runGenerator(['--input', fixture, '--output', output]);
    const remaining = await listFiles(join(output, 'commands'));

    expect(remaining.some((path) => path.includes('/monitors/create/'))).toBe(false);
    expect(remaining.map((path) => relative(join(output, 'commands'), path))).toEqual([
      'monitors/delete.ts',
      'monitors/list.ts',
    ]);
  });
});

async function listFiles(directory: string): Promise<string[]> {
  const output: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) output.push(...(await listFiles(path)));
    else output.push(path);
  }
  return output.sort();
}

async function runGenerator(
  args: string[],
): Promise<{ exitCode: number; stderr: string; stdout: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      process.execPath,
      [
        '--disable-warning=ExperimentalWarning',
        '--experimental-strip-types',
        'scripts/generate-openapi.ts',
        ...args,
      ],
      {
        cwd: projectRoot,
        stdio: ['ignore', 'pipe', 'pipe'],
      },
    );
    let stderr = '';
    let stdout = '';
    child.stderr.setEncoding('utf8').on('data', (chunk) => (stderr += chunk));
    child.stdout.setEncoding('utf8').on('data', (chunk) => (stdout += chunk));
    child.once('error', reject);
    child.once('close', (exitCode) => resolve({ exitCode: exitCode ?? 1, stderr, stdout }));
  });
}
