/**
 * Code generated by scripts/generate-openapi.ts
 * from openapi/openapi.yaml.
 *
 * DO NOT EDIT — changes will be overwritten.
 * Run `pnpm openapi:generate` to regenerate.
 */
import { createOperationCommand } from '../../lib/operation-command.js';
import { operations } from '../../generated/operations.js';

export default createOperationCommand(operations['integrations:update']);
